TRUNCATE TABLE ENROLMENT_CHANGE_PART;
TRUNCATE TABLE ENROLMENT_CHANGE;
TRUNCATE TABLE CACHE_ENROLMENT;

TRUNCATE TABLE ACTIVITY_GROUP;

TRUNCATE TABLE LEARN_MERGED_COURSE; 
TRUNCATE TABLE MODULE_COURSE;  
TRUNCATE TABLE MODULE;

TRUNCATE TABLE VARIANTJTAACTS; 
TRUNCATE TABLE ACTIVITY_PARENTS; 
TRUNCATE TABLE ACTIVITY; 
TRUNCATE TABLE ACTIVITY_TEMPLATE; 
TRUNCATE TABLE ACTIVITY_TYPE;

TRUNCATE TABLE STUDENT_SET; 

TRUNCATE TABLE SYNCHRONISATION_RUN_PREV;
TRUNCATE TABLE SYNCHRONISATION_RUN;