DELETE FROM enrolment_change_part WHERE change_id IN (SELECT change_id FROM ENROLMENT_CHANGE
  WHERE RUN_ID IN (SELECT RUN_ID FROM SYNCHRONISATION_RUN
    WHERE diff_completed IS NULL AND RESULT_CODE='FATAL'));
    
DELETE FROM enrolment_change
  WHERE RUN_ID IN (SELECT RUN_ID FROM SYNCHRONISATION_RUN
    WHERE diff_completed IS NULL AND RESULT_CODE='FATAL');

DELETE FROM cache_enrolment WHERE RUN_ID IN (SELECT RUN_ID FROM SYNCHRONISATION_RUN
  WHERE diff_completed IS NULL AND RESULT_CODE='FATAL');

DELETE FROM synchronisation_run_prev WHERE PREVIOUS_RUN_ID IN (SELECT RUN_ID FROM SYNCHRONISATION_RUN
  WHERE diff_completed IS NULL AND RESULT_CODE='FATAL');

DELETE FROM synchronisation_run_prev WHERE RUN_ID IN (SELECT RUN_ID FROM SYNCHRONISATION_RUN
  WHERE diff_completed IS NULL AND RESULT_CODE='FATAL');
  
DELETE FROM synchronisation_run 
  WHERE diff_completed IS NULL AND RESULT_CODE='FATAL';
  