DELETE FROM ENROLMENT_CHANGE_PART;
DELETE FROM ENROLMENT_CHANGE;
DELETE FROM CACHE_ENROLMENT;

DELETE FROM ACTIVITY_GROUP;

DELETE FROM LEARN_MERGED_COURSE; 
DELETE FROM MODULE_COURSE;  

DELETE FROM VARIANTJTAACTS; 
DELETE FROM ACTIVITY_PARENTS; 
DELETE FROM ACTIVITY; 
DELETE FROM ACTIVITY_TEMPLATE; 
DELETE FROM ACTIVITY_TYPE;

DELETE FROM STUDENT_SET; 
DELETE FROM MODULE;

DELETE FROM SYNCHRONISATION_RUN_PREV;
DELETE FROM SYNCHRONISATION_RUN;