DELETE FROM SATVLE.ENROLMENT_CHANGE_PART WHERE MODULE_COURSE_ID IN (
  SELECT A.MODULE_COURSE_ID
    FROM SATVLE.MODULE_COURSE A
      JOIN SATVLE.MODULE_COURSE B
        ON A.MODULE_COURSE_ID>B.MODULE_COURSE_ID
          AND A.LEARN_COURSE_CODE=B.LEARN_COURSE_CODE
          AND A.TT_MODULE_ID=B.TT_MODULE_ID);

DELETE FROM SATVLE.ACTIVITY_GROUP WHERE MODULE_COURSE_ID IN ( 
  SELECT A.MODULE_COURSE_ID 
    FROM SATVLE.MODULE_COURSE A 
      JOIN SATVLE.MODULE_COURSE B 
        ON A.MODULE_COURSE_ID>B.MODULE_COURSE_ID 
          AND A.LEARN_COURSE_CODE=B.LEARN_COURSE_CODE 
          AND A.TT_MODULE_ID=B.TT_MODULE_ID); 

DELETE FROM SATVLE.MODULE_COURSE  WHERE MODULE_COURSE_ID IN (
  SELECT A.MODULE_COURSE_ID
    FROM SATVLE.MODULE_COURSE A
      JOIN SATVLE.MODULE_COURSE B
        ON A.MODULE_COURSE_ID>B.MODULE_COURSE_ID
          AND A.LEARN_COURSE_CODE=B.LEARN_COURSE_CODE
          AND A.TT_MODULE_ID=B.TT_MODULE_ID);
          