DROP VIEW ACTIVITY_SET_SIZE_VW;
DROP VIEW ADDED_ENROLMENT_VW;
DROP VIEW REMOVED_ENROLMENT_VW;
DROP VIEW SYNC_ACTIVITIES_VW;
DROP VIEW SYNC_STUDENT_SET_VW;
DROP VIEW variant_child_activities_vw;

DROP TABLE ENROLMENT_CHANGE;
DROP TABLE CACHE_ENROLMENT;
DROP TABLE SYNCHRONISATION_RUN;
DROP TABLE VARIANTJTAACTS;
DROP TABLE ACTIVITY;
DROP TABLE MODULE;
DROP TABLE STUDENT_SET;
DROP TABLE ACTIVITY_TEMPLATE;
DROP TABLE ACTIVITY_TYPE;
DROP TABLE CHANGE_RESULT;
DROP TABLE CHANGE_TYPE;

DROP SEQUENCE ENROLMENT_CHANGE_SEQ;
DROP SEQUENCE SYNCHRONISATION_RUN_SEQ;
