
DROP TABLE ACTIVITY_PARENTS;
DROP TABLE ACTIVITY;
DROP TABLE MODULE;
DROP TABLE STUDENT_SET;
DROP TABLE ACTIVITYTYPES;
DROP TABLE TEMPLATE;
DROP TABLE ACTIVITIES_STUDENTSET;
DROP TABLE VARIANTJTAACTS;