DROP VIEW LEARN_GROUP.ADDED_ENROLMENT_VW;
DROP VIEW LEARN_GROUP.REMOVED_ENROLMENT_VW;
DROP VIEW LEARN_GROUP.SYNC_ACTIVITIES_VW;
DROP VIEW LEARN_GROUP.SYNC_STUDENT_SET_VW;
DROP VIEW LEARN_GROUP.ACTIVITY_SET_SIZE_VW;


DROP TABLE LEARN_GROUP.ENROLMENT_CHANGE;
DROP TABLE LEARN_GROUP.CHANGE_RESULT;
DROP TABLE LEARN_GROUP.CHANGE_TYPE;
DROP TABLE LEARN_GROUP.CACHE_ENROLMENT;
DROP TABLE LEARN_GROUP.SYNCHRONISATION_RUN;
DROP TABLE LEARN_GROUP.ACTIVITY;
DROP TABLE LEARN_GROUP.MODULE;
DROP TABLE LEARN_GROUP.ACTIVITY_TEMPLATE;
DROP TABLE LEARN_GROUP.ACTIVITY_TYPE;
DROP TABLE LEARN_GROUP.STUDENT_SET;

DROP SCHEMA LEARN_GROUP;
