DROP VIEW ADDED_ENROLMENT_VW;
DROP VIEW REMOVED_ENROLMENT_VW;
DROP VIEW SYNC_ACTIVITIES_VW;
DROP VIEW SYNC_STUDENT_SET_VW;
DROP VIEW ACTIVITY_SET_SIZE_VW;


DROP TABLE ENROLMENT_CHANGE;
DROP TABLE CHANGE_RESULT;
DROP TABLE CHANGE_TYPE;
DROP TABLE CACHE_ENROLMENT;
DROP TABLE SYNCHRONISATION_RUN;
DROP TABLE ACTIVITY;
DROP TABLE MODULE;
DROP TABLE ACTIVITY_TEMPLATE;
DROP TABLE ACTIVITY_TYPE;
DROP TABLE STUDENT_SET;

